# GET http://localhost:3000/book

# GET http://localhost:3000/newbook

GET http://localhost:3000/book/3

# POST http://localhost:3000/book
# content-type: application/json

# {
#     "name": "Nijika",
#     "author": "Giring",
#     "price": "15000",
#     "release": "2017-11-05"
# }
